### ISSUE TITLE
Additional checks around `. toLowerCase` method.

### ISSUE THREAD

**Issue by nicolad** [scio-labs/use-inkathon#10]
I was trying to deploy https://github.com/scio-labs/inkathon to GH actions and was getting this error:

<img width="1369" alt="image" src="https://user-images.githubusercontent.com/1477453/219784187-dc7e3793-f6d5-4358-adc2-147e34e5a1b0.png">
***

I guess somewhere there is a need for optional chaining operator or some conditionals.

**Comment by wottpal** [comment]
Are you setting the `NEXT_PUBLIC_DEFAULT_CHAIN` environment variable? See https://github.com/scio-labs/inkathon#environment-variables

**Comment by nicolad** [comment]
I created a `.env.production` file based on example and it worked, but what I meant was that the library itself needs to handle the error differently, maybe throw an explicit error that a given env variable wasn't set.
I guess it's not a biggie, but a better DX or better context in case of error message.

**Comment by wottpal** [comment]
Yeah you are right! I opened it again. I mean I explicitly want to throw something (because `NEXT_PUBLIC_DEFAULT_CHAIN` is mandatory), but the message should be more descriptive.

**Comment by wottpal** [comment]
Hey @nicolad, this should be fixed now. I also added a new more descriptive error message when not supplying a `defaultChain` to `UseInkathonProvider`:

<img width="1228" alt="Screenshot 2023-02-21 at 14 50 44" src="https://user-images.githubusercontent.com/3930150/220363647-f17ddf9f-4ecf-4c83-b6ea-6c9c4d34e38f.png">

**Comment by nicolad** [comment]
Thanks, great work 💪
