### ISSUE TITLE
Ability to use 'ecdsa' type instead of the usual 'sr25519'

### ISSUE THREAD

**Issue by corlys** [scio-labs/use-inkathon#14]
Is it possible to use ecdsa type instead of sr25519? Since ink only exposes how to verify ecdsa signatures using `ink::env::ecdsa_recover()` . Its possible to do it on the using polkadotjs's keyrings if we are using polkadotjs library.

```
//using @polkadot/keyring
import { Keyring } from '@polkadot/keyring';

...
// create a keyring with some non-default values specified
const keyring = new Keyring({ type: 'ecdsa' });

...
//using @polkadot/ui-keyring
import keyring from '@polkadot/ui-keyring';
import { cryptoWaitReady } from '@polkadot/util-crypto';

cryptoWaitReady().then(() => {
  // load all available addresses and accounts
  keyring.loadAll({ ss58Format: 42, type: 'sr25519' });

  // additional initialization here, including rendering
});
```
If its possible using this library is there a way to do it?

**Comment by wottpal** [comment]
Hey @corlys what exactly do you want to achieve? You can always just import & use "plain" polkadot.js. This library uses polkadot.js under the hood anyways. And you can use the `keyring` to format addresses however you like.

**Comment by corlys** [comment]
i see, im imagining it will be like the keyrings, you instatiate the hook with the type of ecdsa or sr25519, but you are right i should try with plain polkadot js first.
