### ISSUE TITLE
Unhandled Runtime Error Error: No signer specified, either via api.setSigner or via sign options. You possibly need to pass through an explicit keypair for the origin so it can be used for signing.

### ISSUE THREAD

**Issue by corlys** [scio-labs/use-inkathon#16]
Hey i've been getting this error while calling the contractTx method. The thing is the method sometimes runs no problem and sometimes does not.

Here is the function that calls the contractTx method. [https://github.com/corlys/next-useinkathon/blob/641d6f867bcf50b5176e90746d63e89aa53a7ac3/src/pages/index.tsx#L39](url)

**Comment by wottpal** [comment]
Thanks for bringing this up, @corlys. This is already on my list, as we are experiencing it as well internally. Will be fixed shortly 👍

**Comment by corlys** [comment]
yeah, all fix now i think, thank you for the fix!

**Comment by corlys** [comment]
i'll close this now, thanks again!
