### ISSUE TITLE
Hard to scroll and select accounts at the bottom of the list

### ISSUE THREAD

**Issue by ical10** [scio-labs/use-inkathon#20]
When having a long list of accounts, scroll position is fixed to the top. Thus making it hard to scroll down and select an account at the bottom of the list. "Scrolling" down using arrow key doesn't help either.

https://user-images.githubusercontent.com/14356826/234540705-0b159631-fc3e-4515-84e5-3501341dbc25.mov

Suggested solution:
Set a `max-height` to the container of the list and add an inner scrollbar

**Comment by wottpal** [comment]
Great feedback, @ical10!
Fixed in https://github.com/scio-labs/inkathon/commit/215d76b8fd34766e60f03b485f341c745b106eb7 🫡
