### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by iqbalutomo** [scio-labs/use-inkathon#22]
<img width="496" alt="image" src="https://github.com/scio-labs/use-inkathon/assets/73095492/61e30b0f-2415-47c1-bd82-6ab86e34d87c">

Hello everyone, have you ever experienced an error like this? I tried to call contract using contractTx, maybe someone knows why? Thank you to all of you

**Comment by wottpal** [comment]
@iqbalutomo  

* Do you have your wallet pre-funded with tokens for gas?
* What wallet are you using?
* Can you share more of your code please?

**Comment by iqbalutomo** [comment]
its solved sir, thank you
