### ISSUE TITLE
Questioning the type of balance returned as the formatted balance

### ISSUE THREAD

**Issue by jalooc** [scio-labs/use-inkathon#23]
I really like the utility of your `useBalance()` hook - it's def better thought-through than in the other libraries I've researched so far. Got a doubt about one detail though: I'm wondering if it doesn't make more sense to format the `reducibleBalance` in [here](https://github.com/scio-labs/use-inkathon/blame/91d7564b0bc6d16864761face3e0e538f1c87a4d/src/helpers/getBalance.ts#L96) and thus expose that one as `balanceFormatted`.

The reason for asking is that in my experience, it is more common to display reducible balance rather than the overall balance, because that's effectively what a user can **actually use**. We've had cases in our dapps of users being disoriented by being presented the _raw balance_ and we had to switch to displaying the _reducible balance_.

Alternatively, all balances (`balance`, `reducibleBalance`, `freeBalance` etc.) could be exposed as formatted, if we don't want to choose for the user. Another alternative, if we're afraid of the _complex_ formatting calculation for all of them on every render, could be to let the user choose which balance to format by passing a parameter to the hook (it should be relatively easy to make it type-safe with some generic).

Wdyt?

**Comment by wottpal** [comment]
Agreed. And I think the overhead of computing a couple of more formats is negligible. Added pre-formatted strings for all balance variations in the `BalanceData` in v0.0.8. Please let me know it this works for you :)

**Comment by jalooc** [comment]
Yes, this is perfect. Cheers!
