### ISSUE TITLE
Balance formatting seems to be broken when `fixedDecimals` is set

### ISSUE THREAD

**Issue by jalooc** [scio-labs/use-inkathon#24]
Without `fixedDecimals` (these are correct values):
<img width="580" alt="image" src="https://github.com/scio-labs/use-inkathon/assets/6209244/8bf69209-86be-4e5e-852d-40c926c6d0d0">

With `{ fixedDecimals: 2 }` (order of magnitude is sometimes incorrect, depending on how big the number is):
<img width="576" alt="image" src="https://github.com/scio-labs/use-inkathon/assets/6209244/87ccfbba-e70e-4743-8fcd-ca199a8d39f2">

This is probably a problem with the polkadot library (something related to the `withSi` option of the formatter?), but maybe `use-inkathon` could compensate for it somehow?

**Comment by wottpal** [comment]
@jalooc Thanks for your time posting this :) The inaccuracies I can spot here are:

1. The rounding error that it shows `57.00` instead of `57.02`.
2. That one gives a dot and the other an comma as decimal separator.

Is that what you are referring to?

**Comment by wottpal** [comment]
@jalooc Thanks for reporting! ❤️

Can you check if this behavior is fixed with v0.0.7 for you as well?

**Comment by jalooc** [comment]
Works now, good job 👍 
<img width="591" alt="image" src="https://github.com/scio-labs/use-inkathon/assets/6209244/71374cad-d01d-4454-99d4-1f3276921013">
