### ISSUE TITLE
Incorrect `errorMessage` returned when users cancelled a tx

### ISSUE THREAD

**Issue by ical10** [scio-labs/use-inkathon#35]
When users cancelled a tx, `ContractResult` returns 'Error' instead of 'UserCancelled' as the `errorMessage`.

**Comment by wottpal** [comment]
@ical10 Can you check if this is fixed for azero-id frontend & ink!athon with useInkathon v0.3.0 ([see release](https://github.com/scio-labs/use-inkathon/releases/tag/%40scio-labs%2Fuse-inkathon%400.3.0))? Also do some rough tests as usually regarding the touched parts (i.e. `contractTx`).

**Comment by ical10** [comment]
@wottpal just checked both dapps locally with `use-inkathon@0.3.0`: I can confirm it solved this issue, and `contractTx` is working as expected.

### ink!athon
![inkathon-success-tx](https://github.com/scio-labs/use-inkathon/assets/14356826/86003670-f745-41de-ad4e-438f778cb454)
![inkathon-cancelled-tx](https://github.com/scio-labs/use-inkathon/assets/14356826/53f245d7-1f32-4184-a05d-90d207d71b27)

### azero-id
![azero-id-success-tx](https://github.com/scio-labs/use-inkathon/assets/14356826/b0739ab4-d464-4043-aa3e-b236a4c1b048)
![azero-id-cancelled-tx](https://github.com/scio-labs/use-inkathon/assets/14356826/d39a3448-e863-4abe-ba0b-ae6daea356e7)
