### ISSUE TITLE
Export `isLoading` / `isInitialized` state while connecting to wallet

### ISSUE THREAD

**Issue by MaximilianDietel03** [scio-labs/use-inkathon#7]
Export `isLoading` / `isInitialized` state while connecting to the wallet to be able to display for ex. a Loading Screen

**Comment by wottpal** [comment]
Added `isConnecting`, `isConnected`, and `error` states in https://github.com/scio-labs/use-inkathon/releases/tag/0.0.1-alpha.10. ✅
