### ISSUE TITLE
contractTx with value ?

### ISSUE THREAD

**Issue by dellwatson** [scio-labs/use-inkathon#77]
How to do contractTx and assign value (dot) for sending/transfering the token ?

**Comment by wottpal** [comment]
Just pass it as `value` in the `options` object in [`contractTx`](https://scio-labs.github.io/use-inkathon/functions/contractTx.html). It's really just a convenience wrapper around polkadot.js' `contract.tx` and accepts the same [`ContractOptions`](https://github.com/polkadot-js/api/blob/2ef84c5dcdbbff8aec9ba01e4f13a50130d1a6f3/packages/api-contract/src/types.ts#L82-L86).

Tip: Make sure to pass it as `BigInt` and denominate it with the chains decimals you're using.
