### ISSUE TITLE
contractTx Error  e.asOk.flags.toHuman

### ISSUE THREAD

**Issue by cryingraven** [scio-labs/use-inkathon#85]
An error occured when call contractTx

```js
TypeError: e.asOk.flags.toHuman(...).includes is not a function
    at me (index.js:7:2958)
    at eval (index.js:7:6850)
    at Generator.next (<anonymous>)
    at s (index.js:7:495)
```

**Comment by wottpal** [comment]
Hey @cryingraven, this is an issue introduced by some upstream changes to `@polkadotjs/*` packages (likely somewhere between v12 & v13). I just upgraded & fixed the dependencies in the inkathon Boilerplate in https://github.com/scio-labs/inkathon/commit/b9fb0cddf90538ff8d2a8ab94c6b402ab6923a63. – I welcome any PRs making it compatible with the most recent versions as well!
