### ISSUE TITLE
List of value doesn't return

### ISSUE THREAD

**Issue by ganesh1233456** [scio-labs/use-inkathon#9]
`getname` return this value from `polkadotjs` basically it's a return list.
```
getname (): Result<Vec<GreeterName>, InkPrimitivesLangError>
{ Ok: [ { name: abc age: 10 } ] }
```

But while fetching this value in front end using this code.

```
  // Fetch Name
  const fetchname = async () => {
    if (!contract || !api) return
    setFetchIsLoading(true)
    try {
      const result = await contractQuery(api, '', contract, 'getname')
      const message = unwrapResultOrError<[string]>(result)
      console.log("This is success " + message);
      // setGreeterMessage(message)
    } catch (e) {
      console.error(e)
      toast.error('Error while fetching name. Try again…')
      setGreeterMessage(undefined)
    } finally {
      setFetchIsLoading(false)
    }
  }
```
on print using ` console.log("This is success " + message)` print,

`This is success [object Object]`

Instead list of value. What is wrong here?

**Comment by wottpal** [comment]
Hey @ganesh1233456, happy to help you with ink!athon.

First, can you provide a bit more information:

* The full code of the contract function you're calling
* Please output `result` & `message` as follows in your code:

```js
// …
const result = await contractQuery(api, '', contract, 'getname')
console.log("result", result)
const message = unwrapResultOrError<[string]>(result)
console.log("message", message)
```

Please notice that there is no `+` (string concatenation) when logging the `message`. If `message` really is an object the output you provided above (`[object Object]`) is totally expected in javascript as it's trying to convert an object into a string. So you should log it separately.

What I can say already is that I've tried using `contractQuery` & `unwrapResultOrError` with an array/vector return type just now, and it worked as expected. But we'll figure your problem out anyways.

**Comment by ganesh1233456** [comment]
> Hey @ganesh1233456, happy to help you with ink!athon.
> 
> First, can you provide a bit more information:
> 
> * The full code of the contract function you're calling
> * Please output `result` & `message` as follows in your code:
> 
> ```js
> // …
> const result = await contractQuery(api, '', contract, 'getname')
> console.log("result", result)
> const message = unwrapResultOrError<[string]>(result)
> console.log("message", message)
> ```
> 
> Please notice that there is no `+` (string concatenation) when logging the `message`. If `message` really is an object the output you provided above (`[object Object]`) is totally expected in javascript as it's trying to convert an object into a string. So you should log it separately.
> 
> What I can say already is that I've tried using `contractQuery` & `unwrapResultOrError` with an array/vector return type just now, and it worked as expected. But we'll figure your problem out anyways.

@wottpal thanks for response. The issue is `+` sign now it solves and work as expected. Anyway your response means a lot😁
